#!/bin/sh
# Xsetup - run as root before the login dialog appears

if [ -e /sbin/prime-offload ]; then
    echo running NVIDIA Prime setup /sbin/prime-offload
    /sbin/prime-offload
fi

[ -x /usr/bin/xbrlapi ] && /usr/bin/xbrlapi -q &
[ -x /usr/bin/orca ] && orca &
