#!/bin/bash


ACTION="$1"

shift

PACKAGE_LIST=$@

case $ACTION in
	preInstall)

			if [[ " ${PACKAGE_LIST[*]} " == *" brltty "* ]]; then
				echo " * * Start Pre-Installing brltty * * "
				apt update
				apt install brltty-x11 libbrlapi0.8 python3-brlapi xbrlapi -y
				echo " * * Pre-Installed brltty * * "
			fi
	;;	

	remove)
		errpkg=''
		for pkg in python3-brlapi xbrlapi brltty-x11 brltty libbrlapi0.8 orca
		do
			apt-get remove -y $pkg
			TEST=$( dpkg-query -s $pkg 2> /dev/null| grep Status | cut -d " " -f 4 )
			if [ "$TEST" == 'installed' ];then
				errpkg="$errpkg $pkg"
			fi	
		done
		if [ ${#errpkg} -gt 0 ]
		then
			exit 1
		fi
	;;
esac

